<?php

use Illuminate\Database\Seeder;

class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('questions')->insert([
            ['id' => 1,
                'resultQuery' => "SELECT * FROM Continent",
                'title' => "All Data",
                'topic_id' => 1,
                'qOrder' => 1,
                'erd' => "WorldERD.png"
            ],
            ['id' => 2,
                'resultQuery' => "SELECT name AS 'Country Name', area AS 'Country Area (kilometres squared)', population AS 'Country Population' FROM Country",
                'title' => "Area Populations",
                'topic_id' => 1,
                'qOrder' => 2,
                'erd' => "WorldERD.png"
            ],
            ['id' => 3,
                'resultQuery' => "SELECT name, animal, gender FROM Pet",
                'title' => "Pet Details",
                'topic_id' => 1,
                'qOrder' => 31,
                'erd' => "VetERD.png"
            ],
            ['id' => 4,
                'resultQuery' => "SELECT first_name, last_name, phone_no, address, email FROM Owner",
                'title' => "Owner Details",
                'topic_id' => 1,
                'qOrder' => 32,
                'erd' => "VetERD.png"
            ],
            ['id' => 5,
                'resultQuery' => "SELECT first_name || ' ' || last_name AS 'Vet Name', room_no AS 'Consultation Room', appointment_times AS 'Appointment Availabilities' FROM Vet;",
                'title' => "Vet Appointments",
                'topic_id' => 1,
                'qOrder' => 33,
                'erd' => "VetERD.png"
            ],
            ['id' => 6,
                'resultQuery' => "SELECT * FROM customers",
                'title' => "All Customers",
                'topic_id' => 1,
                'qOrder' => 61,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 7,
                'resultQuery' => "SELECT Name AS 'Artist Name' FROM artists",
                'title' => "Stocked Artists",
                'topic_id' => 1,
                'qOrder' => 62,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 8,
                'resultQuery' => "SELECT FirstName AS 'First Name', LastName AS Surname, Title AS 'Job Title', Email AS 'Email Address' FROM employees",
                'title' => "Update Staff Sheet",
                'topic_id' => 1,
                'qOrder' => 63,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 9,
                'resultQuery' => "SELECT FirstName || ' ' || LastName AS Name, Title AS 'Job Title', Email AS 'Email Address' FROM employees",
                'title' => "Better Staff Sheet",
                'topic_id' => 1,
                'qOrder' => 64,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 10,
                'resultQuery' => "SELECT name, area, population FROM Continent WHERE population > 400000000",
                'title' => "Continent Populations",
                'topic_id' => 2,
                'qOrder' => 1,
                'erd' => "WorldERD.png"
            ],
            ['id' => 11,
                'resultQuery' => "SELECT * FROM Pet WHERE animal = 'Dog'",
                'title' => "Dog Data",
                'topic_id' => 2,
                'qOrder' => 31,
                'erd' => "VetERD.png"
            ],
            ['id' => 12,
                'resultQuery' => "SELECT name, animal, status, owner_id FROM Pet WHERE dob BETWEEN '2013-05-14' AND '2018-05-14'",
                'title' => "Pets 5 for 5",
                'topic_id' => 2,
                'qOrder' => 32,
                'erd' => "VetERD.png"
            ],
            ['id' => 13,
                'resultQuery' => "SELECT FirstName || ' ' || LastName AS Name, Address, State, PostalCode, Country FROM customers WHERE Country = 'Canada'",
                'title' => "Canadian Customers",
                'topic_id' => 2,
                'qOrder' => 61,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 14,
                'resultQuery' => "SELECT FirstName || ' ' || LastName AS Name, Address, State, PostalCode, Country FROM customers WHERE Country = 'France' OR Country = 'Germany'",
                'title' => "French and German Customers",
                'topic_id' => 2,
                'qOrder' => 62,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 15,
                'resultQuery' => "SELECT name, area, population FROM country ORDER BY area DESC",
                'title' => "Country Population",
                'topic_id' => 3,
                'qOrder' => 1,
                'erd' => "WorldERD.png"
            ],
            ['id' => 16,
                'resultQuery' => "SELECT vet_id, id, cost, paid FROM Appointments ORDER BY paid DESC, cost DESC",
                'title' => "Appointment Costs",
                'topic_id' => 3,
                'qOrder' => 31,
                'erd' => "VetERD.png"
            ],
            ['id' => 17,
                'resultQuery' => "SELECT Title, FirstName || ' ' || LastName AS Name FROM employees ORDER BY Title ASC, LastName ASC",
                'title' => "Staff in Order",
                'topic_id' => 3,
                'qOrder' => 61,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 18,
                'resultQuery' => "SELECT MAX(population) FROM Continent;
",
                'title' => "Most Populated",
                'topic_id' => 4,
                'qOrder' => 1,
                'erd' => "WorldERD.png"
            ],
            ['id' => 19,
                'resultQuery' => "SELECT COUNT(id), primary_language FROM Country GROUP BY primary_language ORDER BY primary_language",
                'title' => "Count for language",
                'topic_id' => 5,
                'qOrder' => 1,
                'erd' => "WorldERD.png"
            ],
            ['id' => 20,
                'resultQuery' => "SELECT c1.name AS 'Country Name', c1.area AS 'Country Area', c2.name AS 'Continent Name' FROM Country AS c1 INNER JOIN Continent AS c2 ON c1.continent_id = c2.id",
                'title' => "All the Country data",
                'topic_id' => 6,
                'qOrder' => 1,
                'erd' => "WorldERD.png"
            ],
            ['id' => 21,
                'resultQuery' => "SELECT name FROM Country WHERE continent_id IN (SELECT id FROM Continent WHERE population > 400000000)",
                'title' => "Country Population - IN",
                'topic_id' => 7,
                'qOrder' => 1,
                'erd' => "WorldERD.png"
            ],
            ['id' => 23,
                'resultQuery' => "SELECT SUM(cost) FROM Appointments WHERE paid = 'Yes'",
                'title' => "Sum of Fees",
                'topic_id' => 4,
                'qOrder' => 31,
                'erd' => "VetERD.png"
            ],
            ['id' => 24,
                'resultQuery' => "SELECT MIN(Total) FROM Invoices",
                'title' => "Lowest invoice price",
                'topic_id' => 4,
                'qOrder' => 61,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 25,
                'resultQuery' => "SELECT MAX(UnitPrice) FROM Invoice_items",
                'title' => "Most expensive",
                'topic_id' => 4,
                'qOrder' => 62,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 26,
                'resultQuery' => "SELECT COUNT(id), primary_language FROM Country GROUP BY primary_language HAVING COUNT(id) > 3 ORDER BY primary_language;",
                'title' => "Many Languages",
                'topic_id' => 5,
                'qOrder' => 2,
                'erd' => "WorldERD.png"
            ],
            ['id' => 27,
                'resultQuery' => "SELECT vet_id, SUM(cost) FROM Appointments GROUP BY vet_id HAVING SUM(cost) > 100 ORDER BY SUM(cost) DESC;",
                'title' => "Sean's Mistake",
                'topic_id' => 5,
                'qOrder' => 31,
                'erd' => "VetERD.png"
            ],
            ['id' => 28,
                'resultQuery' => "SELECT composer, COUNT(*) FROM Tracks WHERE milliseconds > 600000 GROUP BY composer;",
                'title' => "Number of tracks",
                'topic_id' => 5,
                'qOrder' => 61,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 29,
                'resultQuery' => "SELECT name FROM Playlists GROUP BY name",
                'title' => "Playlist names",
                'topic_id' => 5,
                'qOrder' => 62,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 30,
                'resultQuery' => "SELECT v.first_name, v.last_name, a.appointment_date, a.cost FROM Vet v INNER JOIN Appointments a ON v.id = a.vet_id WHERE a.paid = 'Yes'",
                'title' => "Sean's Second Mistake",
                'topic_id' => 6,
                'qOrder' => 31,
                'erd' => "VetERD.png"
            ],
            ['id' => 31,
                'resultQuery' => "SELECT e.FirstName || ' ' || e.LastName AS 'Support Rep', c.FirstName || ' ' || c.LastName AS Customer FROM employees AS e INNER JOIN customers AS c WHERE c.SupportRepId = e.EmployeeId ORDER BY e.FirstName, c.FirstName",
                'title' => "Customers Support Rep",
                'topic_id' => 6,
                'qOrder' => 61,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 32,
                'resultQuery' => "SELECT SUM(a.cost) FROM Appointments a WHERE EXISTS (SELECT p.id FROM Pet p WHERE p.id = a.pet_id AND animal = 'Dog')",
                'title' => "Existing Costs",
                'topic_id' => 7,
                'qOrder' => 31,
                'erd' => "VetERD.png"
            ],
            ['id' => 33,
                'resultQuery' => "SELECT name FROM Tracks WHERE genreid IN (SELECT genreid FROM Genres WHERE name = 'Pop')",
                'title' => "Pop music",
                'topic_id' => 7,
                'qOrder' => 61,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 34,
                'resultQuery' => "SELECT firstname, lastname FROM Customers WHERE country = 'USA'",
                'title' => "From the USA",
                'topic_id' => 2,
                'qOrder' => 63,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 35,
                'resultQuery' => "SELECT * FROM Invoices WHERE BillingCountry = 'USA' AND Total > 5",
                'title' => "Billed to the USA",
                'topic_id' => 2,
                'qOrder' => 64,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 36,
                'resultQuery' => "SELECT firstname, lastname FROM Employees WHERE BirthDate BETWEEN '1950-01-01' AND '1970-01-01'",
                'title' => "Old Staff",
                'topic_id' => 2,
                'qOrder' => 65,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 37,
                'resultQuery' => "SELECT name FROM Tracks WHERE composer IS NULL",
                'title' => "Without a composer",
                'topic_id' => 2,
                'qOrder' => 66,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 38,
                'resultQuery' => "SELECT firstname, lastname, company, country FROM Customers WHERE company IS NOT NULL OR country = 'United Kingdom'",
                'title' => "The UK and Unkown",
                'topic_id' => 2,
                'qOrder' => 67,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 39,
                'resultQuery' => "SELECT firstname, lastname FROM Customers ORDER BY lastname",
                'title' => "Last Name order",
                'topic_id' => 3,
                'qOrder' => 62,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 40,
                'resultQuery' => "SELECT name FROM Genres ORDER BY name DESC",
                'title' => "Descending Genre",
                'topic_id' => 3,
                'qOrder' => 63,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 41,
                'resultQuery' => "SELECT BillingCountry, BillingState FROM Invoices ORDER BY BillingCountry, BillingState",
                'title' => "Billed countries then states",
                'topic_id' => 3,
                'qOrder' => 64,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 42,
                'resultQuery' => "SELECT name FROM Tracks WHERE composer = 'Angus Young, Malcolm Young, Brian Johnson' ORDER BY name DESC",
                'title' => "Descending artist",
                'topic_id' => 3,
                'qOrder' => 65,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 43,
                'resultQuery' => "SELECT firstname, lastname, title FROM Employees WHERE Birthdate > '1950-01-01' ORDER BY title ASC, lastname DESC",
                'title' => "Staff by birth",
                'topic_id' => 3,
                'qOrder' => 66,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 44,
                'resultQuery' => "SELECT COUNT(*) FROM Tracks WHERE Composer = 'Queen'",
                'title' => "Queen composed",
                'topic_id' => 4,
                'qOrder' => 63,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 45,
                'resultQuery' => "SELECT AVG(total) FROM Invoices WHERE InvoiceDate BETWEEN '2009-07-01' AND '2010-06-30'",
                'title' => "Average aggregate statement",
                'topic_id' => 4,
                'qOrder' => 64,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 46,
                'resultQuery' => "SELECT SUM(Total) FROM Invoices WHERE BillingCountry = 'Germany'",
                'title' => "Sum aggregate statement",
                'topic_id' => 4,
                'qOrder' => 65,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 47,
                'resultQuery' => "SELECT unitprice, COUNT(*) FROM Tracks GROUP BY unitprice",
                'title' => "Group and aggregate",
                'topic_id' => 5,
                'qOrder' => 63,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 48,
                'resultQuery' => "SELECT BillingCountry, SUM(Total) FROM Invoices GROUP BY BillingCountry HAVING SUM(Total) > 50",
                'title' => "Group By and having",
                'topic_id' => 5,
                'qOrder' => 64,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 49,
                'resultQuery' => "SELECT BillingCountry, AVG(Total) FROM Invoices WHERE BillingState IS NULL GROUP BY BillingCountry HAVING AVG(Total) > 6",
                'title' => "Country bill average",
                'topic_id' => 5,
                'qOrder' => 65,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 50,
                'resultQuery' => "SELECT Albums.title, Artists.name FROM Albums INNER JOIN Artists ON Albums.artistid = Artists.artistid",
                'title' => "Albums and artists",
                'topic_id' => 6,
                'qOrder' => 62,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 51,
                'resultQuery' => "SELECT e1.firstname, e1.lastname, e1.email FROM Employees e1 INNER JOIN Employees e2 ON e1.reportsto = e2.employeeid WHERE e2.firstname = 'Nancy' AND e2.lastname = 'Edwards'",
                'title' => "Nancy's emails",
                'topic_id' => 6,
                'qOrder' => 63,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 52,
                'resultQuery' => "SELECT c.firstname, c.lastname, i.invoicedate FROM Customers c INNER JOIN Invoices i ON c.customerid = i.customerid WHERE i.invoicedate BETWEEN '2009-10-01' AND '2009-12-01'",
                'title' => "Customers late 2009",
                'topic_id' => 6,
                'qOrder' => 64,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 53,
                'resultQuery' => "SELECT t.name AS 'Track', g.name AS 'Genre', m.name AS 'Media Type' FROM Media_types m INNER JOIN Tracks t ON m.mediatypeid = t.mediatypeid INNER JOIN Genres g ON t.genreid = g.genreid WHERE t.composer = 'Queen'",
                'title' => "Queen tracks",
                'topic_id' => 6,
                'qOrder' => 65,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 54,
                'resultQuery' => "SELECT c.firstname, c.lastname, COUNT(i.invoiceid) FROM Customers c INNER JOIN Invoices i ON c.customerid = i.customerid WHERE c.country = 'USA' GROUP BY c.firstname, c.lastname HAVING COUNT(i.invoiceid) > 2",
                'title' => "Customer USA transactions",
                'topic_id' => 6,
                'qOrder' => 66,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 55,
                'resultQuery' => "SELECT title FROM Albums WHERE EXISTS (SELECT name FROM Tracks WHERE Tracks.albumid = Albums.albumid AND Tracks.milliseconds > 600000)",
                'title' => "Long songs",
                'topic_id' => 7,
                'qOrder' => 62,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 56,
                'resultQuery' => "SELECT InvoiceID, InvoiceDate, Total FROM Invoices WHERE Total > (SELECT AVG(Total) FROM Invoices)",
                'title' => "Arithmetic Operation with aggregate",
                'topic_id' => 7,
                'qOrder' => 63,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 57,
                'resultQuery' => "SELECT firstname, lastname, email FROM Customers WHERE supportrepid IN (SELECT employeeid FROM Employees WHERE reportsto IN (SELECT employeeid FROM Employees WHERE firstname = 'Nancy' AND lastname = 'Edwards'))",
                'title' => "Dreaming of Sub-Queries",
                'topic_id' => 7,
                'qOrder' => 64,
                'erd' => "ChinookERD.png"
            ],
            ['id' => 58,
                'resultQuery' => "SELECT i1.BillingAddress, i1.BillingCity, i1.BillingState, i1.BillingCountry, i1.BillingPostalCode, i1.Total FROM Invoices i1, (SELECT AVG(Total) AS t, BillingCountry FROM Invoices GROUP BY BillingCountry) i2 WHERE i1.BillingCountry = i2.BillingCountry AND i1.Total > i2.t",
                'title' => "Join, Aggregate and Group",
                'topic_id' => 7,
                'qOrder' => 65,
                'erd' => "ChinookERD.png"
            ]
        ]);


    }
}
